"""sprint5 baseline: schema completo dos modelos

Revision ID: 5a1b53e0c4d2
Revises: b7c9e1f3a5d2
Create Date: 2026-08-15 17:16:11.377726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1b53e0c4d2'
down_revision = 'b7c9e1f3a5d2'
branch_labels = None
depends_on = None


def upgrade():
    # Banco legado (pré-baseline) já tem o schema materializado pelos runners
    # históricos: deve ser STAMPADO no head, nunca recriado aqui (Sprint 5.3).
    if 'user' in sa.inspect(op.get_bind()).get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autorizacao_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ator_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(length=40), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=20), nullable=False),
    sa.Column('alvo_id', sa.Integer(), nullable=False),
    sa.Column('detalhe', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('autorizacao_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autorizacao_audit_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_autorizacao_audit_user_id'), ['user_id'], unique=False)

    op.create_table('objetivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orgao_tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('permite_raiz', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('orgao_tipo', schema=None) as batch_op:
        batch_op.create_index('ix_orgao_tipo_ativo', ['ativo'], unique=False)
        batch_op.create_index('ix_orgao_tipo_nivel', ['nivel'], unique=False)

    op.create_table('task_access_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=False),
    sa.Column('task_author_user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('attempted_status', sa.String(length=20), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_access_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_access_audit_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_access_audit_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_access_audit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_access_audit_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_access_audit_task_author_user_id'), ['task_author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_access_audit_task_id'), ['task_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('orgao', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('cpf_govbr', sa.String(length=11), nullable=True),
    sa.Column('govbr_sub', sa.String(length=255), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_cpf_govbr'), ['cpf_govbr'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_govbr_sub'), ['govbr_sub'], unique=True)

    op.create_table('StageTemplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('meet_link', sa.String(length=512), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'google_event_id', name='uq_calendar_event_user_google_event')
    )
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_event_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_event_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_calendar_event_user_starts_at', ['user_id', 'starts_at'], unique=False)

    op.create_table('orgao_unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.Column('pai_id', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('codigo_externo', sa.String(length=80), nullable=True),
    sa.Column('data_inicio_vigencia', sa.Date(), nullable=True),
    sa.Column('data_fim_vigencia', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pai_id'], ['orgao_unidade.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_id'], ['orgao_tipo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orgao_unidade', schema=None) as batch_op:
        batch_op.create_index('ix_orgao_unidade_ativo', ['ativo'], unique=False)
        batch_op.create_index('ix_orgao_unidade_codigo_externo', ['codigo_externo'], unique=True)
        batch_op.create_index('ix_orgao_unidade_pai_ordem', ['pai_id', 'ordem'], unique=False)
        batch_op.create_index('ix_orgao_unidade_tipo_id', ['tipo_id'], unique=False)

    op.create_table('project_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('icone', sa.String(length=30), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'nome', name='uq_project_collection_owner_nome')
    )
    with op.batch_alter_table('project_collection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_collection_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('resultado_esperado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('objetivo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['objetivo_id'], ['objetivo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siorg_sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('codigo_raiz', sa.Integer(), nullable=True),
    sa.Column('versao_global', sa.String(length=80), nullable=True),
    sa.Column('hash_manifesto', sa.String(length=128), nullable=True),
    sa.Column('criadas', sa.Integer(), nullable=False),
    sa.Column('atualizadas', sa.Integer(), nullable=False),
    sa.Column('desativadas', sa.Integer(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('usuarios_escopo_zerado', sa.Text(), nullable=True),
    sa.Column('disparado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disparado_por_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('siorg_sync_log', schema=None) as batch_op:
        batch_op.create_index('ix_siorg_sync_log_iniciado_em', ['iniciado_em'], unique=False)

    op.create_table('user_calendar_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(length=500), nullable=True),
    sa.Column('google_account_id', sa.String(length=255), nullable=True),
    sa.Column('google_account_email', sa.String(length=255), nullable=True),
    sa.Column('watch_channel_id', sa.String(length=255), nullable=True),
    sa.Column('watch_resource_id', sa.String(length=255), nullable=True),
    sa.Column('watch_expiration', sa.DateTime(), nullable=True),
    sa.Column('watch_channel_token', sa.String(length=255), nullable=True),
    sa.Column('sync_token', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watch_channel_id')
    )
    with op.batch_alter_table('user_calendar_connection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_calendar_connection_google_account_id'), ['google_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_calendar_connection_user_id'), ['user_id'], unique=True)

    op.create_table('user_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_notification_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notification_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index('ix_user_notification_recipient_read_created', ['recipient_user_id', 'is_read', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notification_recipient_user_id'), ['recipient_user_id'], unique=False)

    op.create_table('StageTemplateItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('templateId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['templateId'], ['StageTemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colecao_sugestao_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('project_ids', sa.JSON(), nullable=False),
    sa.Column('assinatura', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('colecao_id', sa.Integer(), nullable=True),
    sa.Column('modelo_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decidido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['colecao_id'], ['project_collection.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colecao_sugestao_ia', schema=None) as batch_op:
        batch_op.create_index('ix_colecao_sugestao_user_status', ['user_id', 'status'], unique=False)

    op.create_table('indicador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('resultado_esperado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resultado_esperado_id'], ['resultado_esperado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orgao_closure',
    sa.Column('ancestor_id', sa.Integer(), nullable=False),
    sa.Column('descendant_id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ancestor_id'], ['orgao_unidade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['descendant_id'], ['orgao_unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ancestor_id', 'descendant_id')
    )
    with op.batch_alter_table('orgao_closure', schema=None) as batch_op:
        batch_op.create_index('ix_orgao_closure_ancestor_depth', ['ancestor_id', 'depth'], unique=False)
        batch_op.create_index('ix_orgao_closure_descendant', ['descendant_id'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('orgao', sa.String(length=100), nullable=True),
    sa.Column('orgao_id', sa.Integer(), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('objetivo_id', sa.Integer(), nullable=True),
    sa.Column('resultado_esperado_id', sa.Integer(), nullable=True),
    sa.Column('special_project', sa.String(length=50), nullable=True),
    sa.Column('sei_process', sa.String(length=50), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('delivery_type', sa.String(length=50), nullable=True),
    sa.Column('abep_indicator', sa.String(length=255), nullable=True),
    sa.Column('github_link', sa.String(length=500), nullable=True),
    sa.Column('documentation_link', sa.String(length=500), nullable=True),
    sa.Column('product_link', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['objetivo_id'], ['objetivo.id'], ),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgao_unidade.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resultado_esperado_id'], ['resultado_esperado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_orgao_id'), ['orgao_id'], unique=False)

    op.create_table('project_collection_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('orgao_id', sa.Integer(), nullable=True),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['project_collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgao_unidade.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'orgao_id', name='uq_collection_share_orgao'),
    sa.UniqueConstraint('collection_id', 'user_id', name='uq_collection_share_user')
    )
    with op.batch_alter_table('project_collection_share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_collection_share_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_collection_share_orgao_id'), ['orgao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_collection_share_user_id'), ['user_id'], unique=False)

    op.create_table('user_orgao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('orgao_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=10), server_default='gestor', nullable=False),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgao_unidade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'orgao_id', name='uq_user_orgao_user_orgao')
    )
    with op.batch_alter_table('user_orgao', schema=None) as batch_op:
        batch_op.create_index('ix_user_orgao_orgao_id', ['orgao_id'], unique=False)
        batch_op.create_index('ix_user_orgao_user_id', ['user_id'], unique=False)

    op.create_table('etapa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('iniciada', sa.Boolean(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etapa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etapa_entry_type'), ['entry_type'], unique=False)

    op.create_table('indicador_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicador.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_collection_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['project_collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'project_id', name='uq_collection_item')
    )
    with op.batch_alter_table('project_collection_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_collection_item_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_collection_item_project_id'), ['project_id'], unique=False)

    op.create_table('project_custom_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_custom_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_custom_link_project_id'), ['project_id'], unique=False)

    op.create_table('project_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=10), nullable=False),
    sa.Column('origem', sa.String(length=20), server_default='convite', nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    with op.batch_alter_table('project_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_member_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_member_user_id'), ['user_id'], unique=False)

    op.create_table('project_sei_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'numero', name='uq_project_sei_numero')
    )
    with op.batch_alter_table('project_sei_process', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_sei_process_project_id'), ['project_id'], unique=False)

    op.create_table('stage_template_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['StageTemplate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stage_template_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_template_usage_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_template_usage_template_id'), ['template_id'], unique=False)
        batch_op.create_index('ix_stage_template_usage_template_project', ['template_id', 'project_id'], unique=False)

    op.create_table('etapa_responsavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['orgao_unidade.id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etapa_id', 'area_id', name='uq_etapa_responsavel_area')
    )
    with op.batch_alter_table('etapa_responsavel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etapa_responsavel_etapa_id'), ['etapa_id'], unique=False)

    op.create_table('project_stage_meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('calendar_event_id', sa.Integer(), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('google_owner_account_id', sa.String(length=255), nullable=False),
    sa.Column('google_owner_email', sa.String(length=255), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meet_link', sa.String(length=512), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_event.id'], ),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapa.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_stage_meeting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_stage_meeting_calendar_event_id'), ['calendar_event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_stage_meeting_creator_user_id'), ['creator_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_stage_meeting_etapa_id'), ['etapa_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_project_stage_meeting_google_event_id'), ['google_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_stage_meeting_google_owner_account_id'), ['google_owner_account_id'], unique=False)
        batch_op.create_index('ix_project_stage_meeting_owner_google_event', ['google_owner_account_id', 'google_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_stage_meeting_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_stage_meeting_starts_at'), ['starts_at'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsavel', sa.String(length=100), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('etapa_id', sa.Integer(), nullable=True),
    sa.Column('legacy_parent_task_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('tipo_pedido', sa.String(length=30), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapa.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['legacy_parent_task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_etapa_id'), ['etapa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_is_archived'), ['is_archived'], unique=False)

    op.create_table('legacy_task_redirect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legacy_task_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('sample_task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sample_task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legacy_task_redirect', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legacy_task_redirect_legacy_task_id'), ['legacy_task_id'], unique=True)

    op.create_table('task_anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_assignee',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    with op.batch_alter_table('task_assignee', schema=None) as batch_op:
        batch_op.create_index('ix_task_assignee_user_id', ['user_id'], unique=False)

    op.create_table('task_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_comment')
    with op.batch_alter_table('task_assignee', schema=None) as batch_op:
        batch_op.drop_index('ix_task_assignee_user_id')

    op.drop_table('task_assignee')
    op.drop_table('task_anexo')
    with op.batch_alter_table('legacy_task_redirect', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legacy_task_redirect_legacy_task_id'))

    op.drop_table('legacy_task_redirect')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_is_archived'))
        batch_op.drop_index(batch_op.f('ix_task_etapa_id'))

    op.drop_table('task')
    with op.batch_alter_table('project_stage_meeting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_stage_meeting_starts_at'))
        batch_op.drop_index(batch_op.f('ix_project_stage_meeting_project_id'))
        batch_op.drop_index('ix_project_stage_meeting_owner_google_event')
        batch_op.drop_index(batch_op.f('ix_project_stage_meeting_google_owner_account_id'))
        batch_op.drop_index(batch_op.f('ix_project_stage_meeting_google_event_id'))
        batch_op.drop_index(batch_op.f('ix_project_stage_meeting_etapa_id'))
        batch_op.drop_index(batch_op.f('ix_project_stage_meeting_creator_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_stage_meeting_calendar_event_id'))

    op.drop_table('project_stage_meeting')
    with op.batch_alter_table('etapa_responsavel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etapa_responsavel_etapa_id'))

    op.drop_table('etapa_responsavel')
    with op.batch_alter_table('stage_template_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_stage_template_usage_template_project')
        batch_op.drop_index(batch_op.f('ix_stage_template_usage_template_id'))
        batch_op.drop_index(batch_op.f('ix_stage_template_usage_project_id'))

    op.drop_table('stage_template_usage')
    with op.batch_alter_table('project_sei_process', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_sei_process_project_id'))

    op.drop_table('project_sei_process')
    with op.batch_alter_table('project_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_member_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_member_project_id'))

    op.drop_table('project_member')
    op.drop_table('project_history')
    with op.batch_alter_table('project_custom_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_custom_link_project_id'))

    op.drop_table('project_custom_link')
    with op.batch_alter_table('project_collection_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_collection_item_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_collection_item_collection_id'))

    op.drop_table('project_collection_item')
    op.drop_table('indicador_projeto')
    with op.batch_alter_table('etapa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etapa_entry_type'))

    op.drop_table('etapa')
    with op.batch_alter_table('user_orgao', schema=None) as batch_op:
        batch_op.drop_index('ix_user_orgao_user_id')
        batch_op.drop_index('ix_user_orgao_orgao_id')

    op.drop_table('user_orgao')
    with op.batch_alter_table('project_collection_share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_collection_share_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_collection_share_orgao_id'))
        batch_op.drop_index(batch_op.f('ix_project_collection_share_collection_id'))

    op.drop_table('project_collection_share')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_orgao_id'))

    op.drop_table('project')
    with op.batch_alter_table('orgao_closure', schema=None) as batch_op:
        batch_op.drop_index('ix_orgao_closure_descendant')
        batch_op.drop_index('ix_orgao_closure_ancestor_depth')

    op.drop_table('orgao_closure')
    op.drop_table('indicador')
    with op.batch_alter_table('colecao_sugestao_ia', schema=None) as batch_op:
        batch_op.drop_index('ix_colecao_sugestao_user_status')

    op.drop_table('colecao_sugestao_ia')
    op.drop_table('StageTemplateItem')
    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notification_recipient_user_id'))
        batch_op.drop_index('ix_user_notification_recipient_read_created')
        batch_op.drop_index(batch_op.f('ix_user_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_user_notification_event_type'))
        batch_op.drop_index(batch_op.f('ix_user_notification_actor_user_id'))

    op.drop_table('user_notification')
    with op.batch_alter_table('user_calendar_connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_calendar_connection_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_calendar_connection_google_account_id'))

    op.drop_table('user_calendar_connection')
    with op.batch_alter_table('siorg_sync_log', schema=None) as batch_op:
        batch_op.drop_index('ix_siorg_sync_log_iniciado_em')

    op.drop_table('siorg_sync_log')
    op.drop_table('resultado_esperado')
    with op.batch_alter_table('project_collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_collection_owner_user_id'))

    op.drop_table('project_collection')
    with op.batch_alter_table('orgao_unidade', schema=None) as batch_op:
        batch_op.drop_index('ix_orgao_unidade_tipo_id')
        batch_op.drop_index('ix_orgao_unidade_pai_ordem')
        batch_op.drop_index('ix_orgao_unidade_codigo_externo')
        batch_op.drop_index('ix_orgao_unidade_ativo')

    op.drop_table('orgao_unidade')
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_event_user_starts_at')
        batch_op.drop_index(batch_op.f('ix_calendar_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_event_starts_at'))

    op.drop_table('calendar_event')
    op.drop_table('StageTemplate')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_govbr_sub'))
        batch_op.drop_index(batch_op.f('ix_user_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_user_cpf_govbr'))

    op.drop_table('user')
    with op.batch_alter_table('task_access_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_access_audit_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_access_audit_task_author_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_access_audit_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_access_audit_created_at'))
        batch_op.drop_index(batch_op.f('ix_task_access_audit_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_access_audit_action_type'))

    op.drop_table('task_access_audit')
    with op.batch_alter_table('orgao_tipo', schema=None) as batch_op:
        batch_op.drop_index('ix_orgao_tipo_nivel')
        batch_op.drop_index('ix_orgao_tipo_ativo')

    op.drop_table('orgao_tipo')
    op.drop_table('objetivo')
    with op.batch_alter_table('autorizacao_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autorizacao_audit_user_id'))
        batch_op.drop_index(batch_op.f('ix_autorizacao_audit_criado_em'))

    op.drop_table('autorizacao_audit')
    # ### end Alembic commands ###
