"""calendar and task indexes

Revision ID: 8c342aa73f17
Revises: e5f6a7b8c9d0
Create Date: 2026-04-11 20:19:29.587356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c342aa73f17'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etapa_entry_type'), ['entry_type'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_task_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_status'))

    with op.batch_alter_table('task_anexo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_anexo_task_id'))

    with op.batch_alter_table('task_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_comment_task_id'))

    with op.batch_alter_table('user_calendar_connection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_calendar_connection_google_account_id'), ['google_account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_calendar_connection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_calendar_connection_google_account_id'))

    with op.batch_alter_table('task_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_comment_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('task_anexo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_anexo_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_created_by_id'), ['created_by_id'], unique=False)

    with op.batch_alter_table('etapa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etapa_entry_type'))

    # ### end Alembic commands ###
