ROUTE_CASES = [
    # Auth and home
    {
        'id': 'home_get',
        'method': 'GET',
        'rule': '/',
        'path': '/',
        'role': 'user',
        'expected_status': 302,
        'requires_login': False,
        'requires_admin': False,
    },
    {
        'id': 'login_get',
        'method': 'GET',
        'rule': '/login',
        'path': '/login',
        'role': 'anon',
        'expected_status': 200,
        'requires_login': False,
        'requires_admin': False,
    },
    {
        'id': 'login_post',
        'method': 'POST',
        'rule': '/login',
        'path': '/login',
        'role': 'anon',
        'data': {'username': '{user_username}', 'password': '{user_password}'},
        'expected_status': 302,
        'requires_login': False,
        'requires_admin': False,
    },
    {
        'id': 'logout_get',
        'method': 'GET',
        'rule': '/logout',
        'path': '/logout',
        'role': 'user',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'change_password_get',
        'method': 'GET',
        'rule': '/profile/change-password',
        'path': '/profile/change-password',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'change_password_post',
        'method': 'POST',
        'rule': '/profile/change-password',
        'path': '/profile/change-password',
        'role': 'user',
        'data': {
            'current_password': '{user_password}',
            'new_password': 'novaSenha123',
            'confirm_new_password': 'novaSenha123',
        },
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    # Dashboard
    {
        'id': 'dashboard_get',
        'method': 'GET',
        'rule': '/dashboard',
        'path': '/dashboard',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    # Projects
    {
        'id': 'projects_get',
        'method': 'GET',
        'rule': '/projects',
        'path': '/projects',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'projetos_pendentes_get',
        'method': 'GET',
        'rule': '/projetos_pendentes',
        'path': '/projetos_pendentes',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'add_project_post',
        'method': 'POST',
        'rule': '/add_project',
        'path': '/add_project',
        'role': 'user',
        'data': {
            'project_titulo': 'Projeto Criado no Teste',
            'project_area_responsavel': 'Auditoria',
            'project_orgao': 'Orgao Teste',
            'project_prioridade': 'media',
            'project_observacao': 'Observacao de teste',
        },
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'project_detail_get',
        'method': 'GET',
        'rule': '/project/<int:project_id>',
        'path': '/project/{project_id}',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'project_edit_get',
        'method': 'GET',
        'rule': '/project/<int:project_id>/edit',
        'path': '/project/{project_id}/edit',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'project_edit_post',
        'method': 'POST',
        'rule': '/project/<int:project_id>/edit',
        'path': '/project/{project_id}/edit',
        'role': 'user',
        'data': {
            'project_titulo': 'Projeto Editado',
            'project_orgao': 'Orgao Editado',
            'project_area_responsavel': 'Auditoria',
            'project_prioridade': 'alta',
            'project_status': 'Vigente',
            'project_observacao': 'Obs atualizada',
        },
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'project_edit_data_get',
        'method': 'GET',
        'rule': '/project/<int:project_id>/edit_data',
        'path': '/project/{project_id}/edit_data',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'project_update_inline_post',
        'method': 'POST',
        'rule': '/project/<int:project_id>/update_inline',
        'path': '/project/{project_id}/update_inline',
        'role': 'user',
        'json': {'titulo': 'Projeto Inline Atualizado'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'project_delete_post',
        'method': 'POST',
        'rule': '/project/<int:project_id>/delete',
        'path': '/project/{project_id}/delete',
        'role': 'user',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'project_concluir_post',
        'method': 'POST',
        'rule': '/project/<int:project_id>/concluir',
        'path': '/project/{project_complete_id}/concluir',
        'role': 'user',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'project_history_get',
        'method': 'GET',
        'rule': '/project/<int:project_id>/history',
        'path': '/project/{project_id}/history',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    # Etapas
    {
        'id': 'etapa_add_post',
        'method': 'POST',
        'rule': '/project/<int:project_id>/etapa/add',
        'path': '/project/{project_id}/etapa/add',
        'role': 'user',
        'data': {
            'etapa_descricao': 'Nova etapa de teste',
            'etapa_data_inicio': '2026-03-01',
            'etapa_data_fim': '2026-03-05',
            'etapa_responsavel': 'Usuario Auditoria',
        },
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'import_model_post',
        'method': 'POST',
        'rule': '/project/<int:project_id>/import_model',
        'path': '/project/{project_id}/import_model',
        'role': 'user',
        'data': {'template_id': '{template_id}', 'start_date': '2026-03-10'},
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'etapa_edit_get',
        'method': 'GET',
        'rule': '/etapa/<int:etapa_id>/edit',
        'path': '/etapa/{etapa_id}/edit',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'etapa_edit_post',
        'method': 'POST',
        'rule': '/etapa/<int:etapa_id>/edit',
        'path': '/etapa/{etapa_id}/edit',
        'role': 'user',
        'data': {
            'etapa_descricao': 'Etapa editada',
            'etapa_data_inicio': '2026-01-12',
            'etapa_data_fim': '2026-01-18',
            'etapa_responsavel': 'Usuario Auditoria',
            'etapa_comentarios': 'Comentario atualizado',
        },
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'etapa_delete_post',
        'method': 'POST',
        'rule': '/etapa/<int:etapa_id>/delete',
        'path': '/etapa/{etapa_id}/delete',
        'role': 'user',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'etapas_reorder_post',
        'method': 'POST',
        'rule': '/project/<int:project_id>/etapas/reordenar',
        'path': '/project/{project_id}/etapas/reordenar',
        'role': 'user',
        'json': {'etapa_ids': ['{etapa_id}', '{etapa_started_id}']},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'etapa_toggle_iniciada_post',
        'method': 'POST',
        'rule': '/etapa/<int:etapa_id>/toggle_iniciada',
        'path': '/etapa/{etapa_id}/toggle_iniciada',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'etapa_toggle_done_post',
        'method': 'POST',
        'rule': '/etapa/<int:etapa_id>/toggle',
        'path': '/etapa/{etapa_started_id}/toggle',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'etapa_update_field_post',
        'method': 'POST',
        'rule': '/etapa/<int:etapa_id>/update_field',
        'path': '/etapa/{etapa_id}/update_field',
        'role': 'user',
        'json': {'field': 'descricao', 'value': 'Descricao inline'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'etapa_comment_post',
        'method': 'POST',
        'rule': '/etapa/<int:etapa_id>/comentario',
        'path': '/etapa/{etapa_id}/comentario',
        'role': 'user',
        'json': {'comentario': 'Comentario via modal'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'cascade_update_post',
        'method': 'POST',
        'rule': '/project/<int:project_id>/cascade_update',
        'path': '/project/{project_id}/cascade_update',
        'role': 'user',
        'json': {'etapa_id': '{etapa_id}', 'days_diff': 2},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    # Tasks
    {
        'id': 'tasks_get',
        'method': 'GET',
        'rule': '/tarefas',
        'path': '/tarefas',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'tasks_archived_get',
        'method': 'GET',
        'rule': '/tarefas/arquivadas',
        'path': '/tarefas/arquivadas',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'tasks_finalized_get',
        'method': 'GET',
        'rule': '/tarefas/finalizadas',
        'path': '/tarefas/finalizadas',
        'role': 'user',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_add_post',
        'method': 'POST',
        'rule': '/tarefas/add',
        'path': '/tarefas/add',
        'role': 'user',
        'data': {'titulo': 'Tarefa criada no teste', 'project_id': '{project_id}'},
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_detail_get',
        'method': 'GET',
        'rule': '/tarefas/<int:task_id>',
        'path': '/tarefas/{task_id}',
        'role': 'user',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_edit_post',
        'method': 'POST',
        'rule': '/tarefas/<int:task_id>/edit',
        'path': '/tarefas/{task_id}/edit',
        'role': 'user',
        'data': {'titulo': 'Tarefa editada', 'project_id': '{project_id}'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_delete_post',
        'method': 'POST',
        'rule': '/tarefas/<int:task_id>/delete',
        'path': '/tarefas/{task_id}/delete',
        'role': 'user',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_finalize_post',
        'method': 'POST',
        'rule': '/tarefas/<int:task_id>/finalizar',
        'path': '/tarefas/{task_id}/finalizar',
        'role': 'user',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_reactivate_post',
        'method': 'POST',
        'rule': '/tarefas/<int:task_id>/reativar',
        'path': '/tarefas/{task_id}/reativar',
        'role': 'user',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_item_add_post',
        'method': 'POST',
        'rule': '/tarefas/<int:task_id>/itens/add',
        'path': '/tarefas/{task_id}/itens/add',
        'role': 'user',
        'headers': {'X-Requested-With': 'XMLHttpRequest'},
        'data': {
            'descricao': 'Item novo',
            'status': 'nao_iniciada',
            'responsavel': 'Usuario Auditoria',
        },
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_item_global_add_post',
        'method': 'POST',
        'rule': '/tarefas/itens/add',
        'path': '/tarefas/itens/add',
        'role': 'user',
        'headers': {'X-Requested-With': 'XMLHttpRequest'},
        'data': {
            'project': '{project_id}',
            'descricao': 'Item global novo',
            'status': 'nao_iniciada',
            'responsavel': 'Usuario Auditoria',
        },
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_item_edit_post',
        'method': 'POST',
        'rule': '/tarefas/itens/<int:item_id>/edit',
        'path': '/tarefas/itens/{task_item_id}/edit',
        'role': 'user',
        'data': {
            'descricao': 'Item editado',
            'status': 'para_validacao',
            'responsavel': 'Usuario Auditoria',
        },
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_item_delete_post',
        'method': 'POST',
        'rule': '/tarefas/itens/<int:item_id>/delete',
        'path': '/tarefas/itens/{task_item_id}/delete',
        'role': 'user',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_item_update_status_post',
        'method': 'POST',
        'rule': '/tarefas/itens/<int:item_id>/update_status',
        'path': '/tarefas/itens/{task_item_id}/update_status',
        'role': 'user',
        'json': {'status': 'em_andamento'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_update_status_post',
        'method': 'POST',
        'rule': '/tarefas/<int:task_id>/update_status',
        'path': '/tarefas/{task_item_id}/update_status',
        'role': 'user',
        'json': {'status': 'em_andamento'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_item_update_prioridade_post',
        'method': 'POST',
        'rule': '/tarefas/itens/<int:item_id>/update_prioridade',
        'path': '/tarefas/itens/{task_item_id}/update_prioridade',
        'role': 'user',
        'json': {'prioridade': 'alta'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_update_prioridade_post',
        'method': 'POST',
        'rule': '/tarefas/<int:task_id>/update_prioridade',
        'path': '/tarefas/{task_item_id}/update_prioridade',
        'role': 'user',
        'json': {'prioridade': 'alta'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_item_update_tipo_post',
        'method': 'POST',
        'rule': '/tarefas/itens/<int:item_id>/update_tipo',
        'path': '/tarefas/itens/{task_item_id}/update_tipo',
        'role': 'user',
        'json': {'tipo_pedido': 'bug'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_update_tipo_post',
        'method': 'POST',
        'rule': '/tarefas/<int:task_id>/update_tipo',
        'path': '/tarefas/{task_item_id}/update_tipo',
        'role': 'user',
        'json': {'tipo_pedido': 'bug'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'tasks_reorder_post',
        'method': 'POST',
        'rule': '/tarefas/reordenar',
        'path': '/tarefas/reordenar',
        'role': 'user',
        'json': {'ordem': ['{task_id}']},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_items_reorder_post',
        'method': 'POST',
        'rule': '/tarefas/<int:task_id>/itens/reordenar',
        'path': '/tarefas/{task_id}/itens/reordenar',
        'role': 'user',
        'json': {'ordem': ['{task_item_id}']},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_item_comment_add_post',
        'method': 'POST',
        'rule': '/tarefas/itens/<int:item_id>/comentarios/add',
        'path': '/tarefas/itens/{task_item_id}/comentarios/add',
        'role': 'user',
        'headers': {'X-Requested-With': 'XMLHttpRequest'},
        'data': {'content': 'Comentario criado no teste'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_comment_add_post',
        'method': 'POST',
        'rule': '/tarefas/<int:task_id>/comentarios/add',
        'path': '/tarefas/{task_item_id}/comentarios/add',
        'role': 'user',
        'headers': {'X-Requested-With': 'XMLHttpRequest'},
        'data': {'content': 'Comentario canonico'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_comment_edit_post',
        'method': 'POST',
        'rule': '/tarefas/comentarios/<int:comment_id>/edit',
        'path': '/tarefas/comentarios/{comment_id}/edit',
        'role': 'user',
        'headers': {'X-Requested-With': 'XMLHttpRequest'},
        'data': {'content': 'Comentario editado'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_comment_delete_post',
        'method': 'POST',
        'rule': '/tarefas/comentarios/<int:comment_id>/delete',
        'path': '/tarefas/comentarios/{comment_id}/delete',
        'role': 'user',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'project_tasks_get',
        'method': 'GET',
        'rule': '/projeto/<int:project_id>/tarefas',
        'path': '/projeto/{project_id}/tarefas',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_assignable_users_get',
        'method': 'GET',
        'rule': '/tarefas/<int:task_id>/sugestoes-responsavel',
        'path': '/tarefas/{task_id}/sugestoes-responsavel',
        'role': 'user',
        'query_string': {'q': 'Usuario'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_hub_assignable_users_get',
        'method': 'GET',
        'rule': '/tarefas/sugestoes-responsavel',
        'path': '/tarefas/sugestoes-responsavel',
        'role': 'user',
        'query_string': {'project': '{project_id}', 'q': 'Usuario'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_item_anexos_list_get',
        'method': 'GET',
        'rule': '/tarefas/itens/<int:item_id>/anexos',
        'path': '/tarefas/itens/{task_item_id}/anexos',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_anexos_list_get',
        'method': 'GET',
        'rule': '/tarefas/<int:task_id>/anexos',
        'path': '/tarefas/{task_item_id}/anexos',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_item_anexo_add_post',
        'method': 'POST',
        'rule': '/tarefas/itens/<int:item_id>/anexos/add',
        'path': '/tarefas/itens/{task_item_id}/anexos/add',
        'role': 'user',
        'expected_status': 400,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_anexo_add_post',
        'method': 'POST',
        'rule': '/tarefas/<int:task_id>/anexos/add',
        'path': '/tarefas/{task_item_id}/anexos/add',
        'role': 'user',
        'expected_status': 400,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_archive_finalizadas_post',
        'method': 'POST',
        'rule': '/tarefas/arquivar-finalizadas',
        'path': '/tarefas/arquivar-finalizadas',
        'role': 'user',
        'data': {'project': '{project_id}'},
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_desarquivar_post',
        'method': 'POST',
        'rule': '/tarefas/<int:task_id>/desarquivar',
        'path': '/tarefas/{task_item_id}/desarquivar',
        'role': 'user',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_item_anexo_view_get',
        'method': 'GET',
        'rule': '/tarefas/anexos/<int:anexo_id>',
        'path': '/tarefas/anexos/999999',
        'role': 'user',
        'expected_status': 404,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'task_item_anexo_delete_post',
        'method': 'POST',
        'rule': '/tarefas/anexos/<int:anexo_id>/delete',
        'path': '/tarefas/anexos/999999/delete',
        'role': 'user',
        'expected_status': 404,
        'requires_login': True,
        'requires_admin': False,
    },
    # API and search
    {
        'id': 'api_resultados_get',
        'method': 'GET',
        'rule': '/api/resultados/<int:objetivo_id>',
        'path': '/api/resultados/1',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'api_indicadores_get',
        'method': 'GET',
        'rule': '/api/indicadores/<int:resultado_id>',
        'path': '/api/indicadores/1',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'api_templates_get',
        'method': 'GET',
        'rule': '/api/templates',
        'path': '/api/templates',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'api_template_stages_get',
        'method': 'GET',
        'rule': '/api/templates/<int:template_id>',
        'path': '/api/templates/{template_id}',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'api_user_projects_get',
        'method': 'GET',
        'rule': '/api/projetos_usuario',
        'path': '/api/projetos_usuario',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'api_busca_global_get',
        'method': 'GET',
        'rule': '/api/busca-global',
        'path': '/api/busca-global',
        'role': 'user',
        'query_string': {'q': 'Projeto'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'busca_page_get',
        'method': 'GET',
        'rule': '/busca',
        'path': '/busca',
        'role': 'user',
        'query_string': {'q': 'Projeto'},
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    {
        'id': 'notifications_dropdown_post',
        'method': 'POST',
        'rule': '/api/notificacoes/dropdown',
        'path': '/api/notificacoes/dropdown',
        'role': 'user',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': False,
    },
    # Admin users
    {
        'id': 'admin_users_get',
        'method': 'GET',
        'rule': '/admin/users',
        'path': '/admin/users',
        'role': 'admin',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_users_add_get',
        'method': 'GET',
        'rule': '/admin/users/add',
        'path': '/admin/users/add',
        'role': 'admin',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_users_add_post',
        'method': 'POST',
        'rule': '/admin/users/add',
        'path': '/admin/users/add',
        'role': 'admin',
        'data': {
            'username': 'novo_usuario_teste',
            'name': 'Novo Usuario',
            'password': 'senhaNova123',
            'orgao': 'Orgao Novo',
            'areas_responsavel': ['Auditoria'],
        },
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_users_edit_get',
        'method': 'GET',
        'rule': '/admin/users/edit/<int:user_id>',
        'path': '/admin/users/edit/{editable_user_id}',
        'role': 'admin',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_users_edit_post',
        'method': 'POST',
        'rule': '/admin/users/edit/<int:user_id>',
        'path': '/admin/users/edit/{editable_user_id}',
        'role': 'admin',
        'data': {
            'name': 'Usuario Editado',
            'orgao': 'Orgao Editado',
            'areas_responsavel': ['Auditoria'],
        },
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_users_delete_post',
        'method': 'POST',
        'rule': '/admin/users/delete/<int:user_id>',
        'path': '/admin/users/delete/{deletable_user_id}',
        'role': 'admin',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': True,
    },
    # Admin areas
    {
        'id': 'admin_areas_get',
        'method': 'GET',
        'rule': '/admin/areas',
        'path': '/admin/areas',
        'role': 'admin',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_areas_new_get',
        'method': 'GET',
        'rule': '/admin/areas/new',
        'path': '/admin/areas/new',
        'role': 'admin',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_areas_new_post',
        'method': 'POST',
        'rule': '/admin/areas/new',
        'path': '/admin/areas/new',
        'role': 'admin',
        'data': {
            'name': 'Area Nova Teste',
        },
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_areas_edit_get',
        'method': 'GET',
        'rule': '/admin/areas/<int:area_id>/edit',
        'path': '/admin/areas/{vpe_area_id}/edit',
        'role': 'admin',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_areas_edit_post',
        'method': 'POST',
        'rule': '/admin/areas/<int:area_id>/edit',
        'path': '/admin/areas/{vpe_area_id}/edit',
        'role': 'admin',
        'data': {
            'name': 'VPE Ajustada',
        },
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_areas_delete_post',
        'method': 'POST',
        'rule': '/admin/areas/<int:area_id>/delete',
        'path': '/admin/areas/{vpe_area_id}/delete',
        'role': 'admin',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': True,
    },
    # Admin templates
    {
        'id': 'admin_templates_get',
        'method': 'GET',
        'rule': '/admin/templates',
        'path': '/admin/templates',
        'role': 'admin',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_templates_new_get',
        'method': 'GET',
        'rule': '/admin/templates/new',
        'path': '/admin/templates/new',
        'role': 'admin',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_templates_new_post',
        'method': 'POST',
        'rule': '/admin/templates/new',
        'path': '/admin/templates/new',
        'role': 'admin',
        'data': {
            'name': 'Template Novo',
            'description': 'Criado nos testes',
            'stage_name': ['Etapa A'],
            'stage_duration': ['2'],
        },
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_templates_edit_get',
        'method': 'GET',
        'rule': '/admin/templates/<int:template_id>/edit',
        'path': '/admin/templates/{template_id}/edit',
        'role': 'admin',
        'expected_status': 200,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_templates_edit_post',
        'method': 'POST',
        'rule': '/admin/templates/<int:template_id>/edit',
        'path': '/admin/templates/{template_id}/edit',
        'role': 'admin',
        'data': {
            'name': 'Template Editado',
            'description': 'Atualizado nos testes',
            'stage_name': ['Etapa B'],
            'stage_duration': ['4'],
        },
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': True,
    },
    {
        'id': 'admin_templates_delete_post',
        'method': 'POST',
        'rule': '/admin/templates/<int:template_id>/delete',
        'path': '/admin/templates/{template_id}/delete',
        'role': 'admin',
        'expected_status': 302,
        'requires_login': True,
        'requires_admin': True,
    },
    # Maintenance
    {
        'id': 'favicon_get',
        'method': 'GET',
        'rule': '/favicon.ico',
        'path': '/favicon.ico',
        'role': 'anon',
        'expected_status': [200, 404],
        'requires_login': False,
        'requires_admin': False,
    },
    {
        'id': 'setup_db_get',
        'method': 'GET',
        'rule': '/setup_db',
        'path': '/setup_db',
        'role': 'anon',
        'expected_status': 200,
        'requires_login': False,
        'requires_admin': False,
    },
]

LOGIN_REQUIRED_CASES = [case for case in ROUTE_CASES if case['requires_login']]
ADMIN_REQUIRED_CASES = [case for case in ROUTE_CASES if case['requires_admin']]

# Segurança adicional para garantir escopo fechado do plano.
assert len(ROUTE_CASES) == 93
