ROUTE_CASES = [
    # Auth and home
    {
        "id": "home_get",
        "method": "GET",
        "rule": "/",
        "path": "/",
        "role": "user",
        "expected_status": 302,
        "requires_login": False,
        "requires_admin": False,
    },
    {
        "id": "login_get",
        "method": "GET",
        "rule": "/login",
        "path": "/login",
        "role": "anon",
        "expected_status": 200,
        "requires_login": False,
        "requires_admin": False,
    },
    {
        "id": "login_post",
        "method": "POST",
        "rule": "/login",
        "path": "/login",
        "role": "anon",
        "data": {"username": "{user_username}", "password": "{user_password}"},
        "expected_status": 302,
        "requires_login": False,
        "requires_admin": False,
    },
    {
        "id": "login_govbr_get",
        "method": "GET",
        "rule": "/login/govbr",
        "path": "/login/govbr",
        "role": "anon",
        "expected_status": 302,
        "requires_login": False,
        "requires_admin": False,
    },
    {
        "id": "login_govbr_callback_get",
        "method": "GET",
        "rule": "/auth/govbr/callback",
        "path": "/auth/govbr/callback",
        "role": "anon",
        "expected_status": 302,
        "requires_login": False,
        "requires_admin": False,
    },
    {
        "id": "logout_get",
        "method": "GET",
        "rule": "/logout",
        "path": "/logout",
        "role": "user",
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "change_password_get",
        "method": "GET",
        "rule": "/profile/change-password",
        "path": "/profile/change-password",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "change_password_post",
        "method": "POST",
        "rule": "/profile/change-password",
        "path": "/profile/change-password",
        "role": "user",
        "data": {
            "current_password": "{user_password}",
            "new_password": "novaSenha123",
            "confirm_new_password": "novaSenha123",
        },
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    # Dashboard
    {
        "id": "dashboard_get",
        "method": "GET",
        "rule": "/dashboard",
        "path": "/dashboard",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "chatbot_token_get",
        "method": "GET",
        "rule": "/api/chatbot-token",
        "path": "/api/chatbot-token",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    # Projects
    {
        "id": "projects_get",
        "method": "GET",
        "rule": "/projects",
        "path": "/projects",
        "role": "user",
        # KEEP-ENDPOINT: /projects virou redirect 302 -> /projetos (SPA).
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "projects_download_get",
        "method": "GET",
        "rule": "/projects/download",
        "path": "/projects/download",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "project_detail_get",
        "method": "GET",
        "rule": "/project/<int:project_id>",
        "path": "/project/{project_id}",
        "role": "user",
        # KEEP-ENDPOINT: redireciona (302) para /projetos/<id> na SPA — preserva
        # target_url persistido em notificações e links da busca.
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    # Etapas
    {
        "id": "project_meeting_add_post",
        "method": "POST",
        "rule": "/project/<int:project_id>/meeting/add",
        "path": "/project/{project_id}/meeting/add",
        "role": "user",
        "data": {
            "title": "Reuniao de teste",
            "starts_at": "2026-03-10T09:00",
            "ends_at": "2026-03-10T10:00",
            "location": "Sala 2",
        },
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "project_meeting_edit_post",
        "method": "POST",
        "rule": "/etapa/<int:etapa_id>/meeting/edit",
        "path": "/etapa/{etapa_id}/meeting/edit",
        "role": "user",
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "import_model_post",
        "method": "POST",
        "rule": "/project/<int:project_id>/import_model",
        "path": "/project/{project_id}/import_model",
        "role": "user",
        "data": {"template_id": "{template_id}", "start_date": "2026-03-10"},
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    # Tasks
    {
        "id": "tasks_get",
        "method": "GET",
        "rule": "/tarefas",
        "path": "/tarefas",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "tasks_archived_get",
        "method": "GET",
        "rule": "/tarefas/arquivadas",
        "path": "/tarefas/arquivadas",
        "role": "user",
        # Redirect resolver 302 -> /tarefas?modo=arquivadas (a SPA nao tem rota
        # client-side /tarefas/arquivadas; o modo e lido do query param).
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "tasks_finalized_get",
        "method": "GET",
        "rule": "/tarefas/finalizadas",
        "path": "/tarefas/finalizadas",
        "role": "user",
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "task_detail_get",
        "method": "GET",
        "rule": "/tarefas/<int:task_id>",
        "path": "/tarefas/{task_id}",
        "role": "user",
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "task_comment_add_post",
        "method": "POST",
        "rule": "/tarefas/<int:task_id>/comentarios/add",
        "path": "/tarefas/{task_item_id}/comentarios/add",
        "role": "user",
        "headers": {"X-Requested-With": "XMLHttpRequest"},
        "data": {"content": "Comentario canonico"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "task_comment_edit_post",
        "method": "POST",
        "rule": "/tarefas/comentarios/<int:comment_id>/edit",
        "path": "/tarefas/comentarios/{comment_id}/edit",
        "role": "user",
        "headers": {"X-Requested-With": "XMLHttpRequest"},
        "data": {"content": "Comentario editado"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "task_comment_delete_post",
        "method": "POST",
        "rule": "/tarefas/comentarios/<int:comment_id>/delete",
        "path": "/tarefas/comentarios/{comment_id}/delete",
        "role": "user",
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "project_tasks_get",
        "method": "GET",
        "rule": "/projeto/<int:project_id>/tarefas",
        "path": "/projeto/{project_id}/tarefas",
        "role": "user",
        # Redirect resolver 302 -> /tarefas?project=<id> (a SPA nao tem rota
        # client-side /projeto/<id>/tarefas; o filtro e lido do query param).
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "task_project_etapas_get",
        "method": "GET",
        "rule": "/tarefas/projeto/<int:project_id>/etapas",
        "path": "/tarefas/projeto/{project_id}/etapas",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "task_anexos_list_get",
        "method": "GET",
        "rule": "/tarefas/<int:task_id>/anexos",
        "path": "/tarefas/{task_item_id}/anexos",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "task_anexo_add_post",
        "method": "POST",
        "rule": "/tarefas/<int:task_id>/anexos/add",
        "path": "/tarefas/{task_item_id}/anexos/add",
        "role": "user",
        "expected_status": 400,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "task_item_anexo_view_get",
        "method": "GET",
        "rule": "/tarefas/anexos/<int:anexo_id>",
        "path": "/tarefas/anexos/999999",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "task_item_anexo_delete_post",
        "method": "POST",
        "rule": "/tarefas/anexos/<int:anexo_id>/delete",
        "path": "/tarefas/anexos/999999/delete",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    # Calendars
    {
        "id": "calendars_hub_get",
        "method": "GET",
        "rule": "/calendarios",
        "path": "/calendarios",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "calendar_oauth_start_get",
        "method": "GET",
        "rule": "/calendar/oauth/start",
        "path": "/calendar/oauth/start",
        "role": "user",
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "calendar_oauth_callback_get",
        "method": "GET",
        "rule": "/calendar/oauth/callback",
        "path": "/calendar/oauth/callback",
        "role": "user",
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "calendar_google_disconnect_post",
        "method": "POST",
        "rule": "/calendarios/google/disconnect",
        "path": "/calendarios/google/disconnect",
        "role": "user",
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "calendar_google_sync_post",
        "method": "POST",
        "rule": "/calendarios/google/sync",
        "path": "/calendarios/google/sync",
        "role": "user",
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "calendar_google_watch_renew_post",
        "method": "POST",
        "rule": "/calendarios/google/watch/renew",
        "path": "/calendarios/google/watch/renew",
        "role": "user",
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "calendar_event_create_post",
        "method": "POST",
        "rule": "/calendarios/eventos",
        "path": "/calendarios/eventos",
        "role": "user",
        "data": {
            "title": "Evento de teste",
            "location": "Auditorio",
            "starts_at": "2026-03-20T09:00",
            "ends_at": "2026-03-20T10:00",
            "description": "Gerado pela matriz de rotas",
        },
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "calendar_event_edit_post",
        "method": "POST",
        "rule": "/calendarios/eventos/<int:event_id>/editar",
        "path": "/calendarios/eventos/{calendar_event_id}/editar",
        "role": "user",
        "data": {
            "title": "Evento alterado",
            "location": "Sala de reuniao",
            "starts_at": "2026-03-20T11:00",
            "ends_at": "2026-03-20T12:00",
            "description": "Atualizacao via matriz",
        },
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "calendar_event_delete_post",
        "method": "POST",
        "rule": "/calendarios/eventos/<int:event_id>/excluir",
        "path": "/calendarios/eventos/{calendar_event_id}/excluir",
        "role": "user",
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "calendar_webhook_post",
        "method": "POST",
        "rule": "/webhook",
        "path": "/webhook",
        "role": "anon",
        "expected_status": 400,
        "requires_login": False,
        "requires_admin": False,
    },
    # SPA API (envelope canônico)
    {
        "id": "api_me_get",
        "method": "GET",
        "rule": "/api/me",
        "path": "/api/me",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_csrf_token_get",
        "method": "GET",
        "rule": "/api/csrf-token",
        "path": "/api/csrf-token",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_dashboard_get",
        "method": "GET",
        "rule": "/api/dashboard",
        "path": "/api/dashboard",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projetos_pendentes_get",
        "method": "GET",
        "rule": "/api/projetos-pendentes",
        "path": "/api/projetos-pendentes",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projeto_historico_get",
        "method": "GET",
        "rule": "/api/projetos/<int:project_id>/historico",
        "path": "/api/projetos/{project_id}/historico",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projetos_get",
        "method": "GET",
        "rule": "/api/projetos",
        "path": "/api/projetos",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projeto_detalhe_get",
        "method": "GET",
        "rule": "/api/projetos/<int:project_id>/detalhe",
        "path": "/api/projetos/{project_id}/detalhe",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projeto_inline_post",
        "method": "POST",
        "rule": "/api/projetos/<int:project_id>/inline",
        "path": "/api/projetos/{project_id}/inline",
        "role": "user",
        "json": {"titulo": "Projeto Inline API"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projeto_tarefas_etapa_get",
        "method": "GET",
        "rule": "/api/projetos/<int:project_id>/tarefas-etapa",
        "path": "/api/projetos/{project_id}/tarefas-etapa",
        "role": "user",
        "query_string": {"etapa_id": "{etapa_id}"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_etapa_add_post",
        "method": "POST",
        "rule": "/api/projetos/<int:project_id>/etapas",
        "path": "/api/projetos/{project_id}/etapas",
        "role": "user",
        "json": {
            "descricao": "Etapa via API",
            "data_inicio": "2026-03-02",
            "data_fim": "2026-03-06",
            "responsavel": "Usuario Auditoria",
            "responsaveis": [{"area_id": None, "label": "Outras"}],
        },
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_etapa_edit_post",
        "method": "POST",
        "rule": "/api/etapas/<int:etapa_id>",
        "path": "/api/etapas/{etapa_id}",
        "role": "user",
        "json": {
            "descricao": "Etapa editada via API",
            "data_inicio": "2026-01-12",
            "data_fim": "2026-01-16",
            "responsavel": "Usuario Auditoria",
            "iniciada": False,
            "done": False,
        },
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_etapa_delete_post",
        "method": "POST",
        "rule": "/api/etapas/<int:etapa_id>/delete",
        "path": "/api/etapas/{etapa_id}/delete",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_etapa_update_field_post",
        "method": "POST",
        "rule": "/api/etapas/<int:etapa_id>/update-field",
        "path": "/api/etapas/{etapa_id}/update-field",
        "role": "user",
        "json": {"field": "descricao", "value": "Descricao inline API"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_etapa_comentario_post",
        "method": "POST",
        "rule": "/api/etapas/<int:etapa_id>/comentario",
        "path": "/api/etapas/{etapa_id}/comentario",
        "role": "user",
        "json": {"comentario": "Comentario via API"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_etapa_toggle_iniciada_post",
        "method": "POST",
        "rule": "/api/etapas/<int:etapa_id>/toggle-iniciada",
        "path": "/api/etapas/{etapa_id}/toggle-iniciada",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_etapa_toggle_post",
        "method": "POST",
        "rule": "/api/etapas/<int:etapa_id>/toggle",
        "path": "/api/etapas/{etapa_id}/toggle",
        "role": "user",
        "expected_status": 422,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_etapa_responsaveis_post",
        "method": "POST",
        "rule": "/api/etapas/<int:etapa_id>/responsaveis",
        "path": "/api/etapas/{etapa_id}/responsaveis",
        "role": "user",
        "json": {"areas": [{"area_id": None, "label": "Outras"}]},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_areas_get",
        "method": "GET",
        "rule": "/api/areas",
        "path": "/api/areas",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_etapas_reordenar_post",
        "method": "POST",
        "rule": "/api/projetos/<int:project_id>/etapas/reordenar",
        "path": "/api/projetos/{project_id}/etapas/reordenar",
        "role": "user",
        "json": {
            "etapa_ids": ["{etapa_id}", "{etapa_started_id}"],
            "etapa_id": "{etapa_id}",
            "days_diff": 2,
        },
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projeto_cascade_post",
        "method": "POST",
        "rule": "/api/projetos/<int:project_id>/cascade",
        "path": "/api/projetos/{project_id}/cascade",
        "role": "user",
        "json": {"etapa_id": "{etapa_id}", "days_diff": 2},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projeto_importar_modelo_post",
        "method": "POST",
        "rule": "/api/projetos/<int:project_id>/importar-modelo",
        "path": "/api/projetos/{project_id}/importar-modelo",
        "role": "user",
        "json": {"template_id": "{template_id}", "start_date": "2026-03-10"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_etapas_templates_get",
        "method": "GET",
        "rule": "/api/etapas/templates",
        "path": "/api/etapas/templates",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefas_get",
        "method": "GET",
        "rule": "/api/tarefas",
        "path": "/api/tarefas",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefas_board_get",
        "method": "GET",
        "rule": "/api/tarefas/board",
        "path": "/api/tarefas/board",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefa_status_post",
        "method": "POST",
        "rule": "/api/tarefas/<int:task_id>/status",
        "path": "/api/tarefas/{task_id}/status",
        "role": "user",
        "json": {"status": "em_andamento"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefas_board_reordenar_post",
        "method": "POST",
        "rule": "/api/tarefas/board/reordenar",
        "path": "/api/tarefas/board/reordenar",
        "role": "user",
        "json": {
            "columns": [
                {"status": "nao_iniciada", "task_ids": ["{task_id}"]},
            ]
        },
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    # Fase 5b-2 (Drawer de Tarefa): detalhe + edicao inline (autosave) + lifecycle.
    {
        "id": "api_tarefa_detalhe_get",
        "method": "GET",
        "rule": "/api/tarefas/<int:task_id>/detalhe",
        "path": "/api/tarefas/{task_id}/detalhe",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefa_campos_post",
        "method": "POST",
        "rule": "/api/tarefas/<int:task_id>/campos",
        "path": "/api/tarefas/{task_id}/campos",
        "role": "user",
        "json": {"descricao": "Tarefa editada via drawer"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefa_finalizar_post",
        "method": "POST",
        "rule": "/api/tarefas/<int:task_id>/finalizar",
        "path": "/api/tarefas/{task_id}/finalizar",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefa_arquivar_post",
        "method": "POST",
        "rule": "/api/tarefas/<int:task_id>/arquivar",
        "path": "/api/tarefas/{task_id}/arquivar",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefa_desarquivar_post",
        "method": "POST",
        "rule": "/api/tarefas/<int:task_id>/desarquivar",
        "path": "/api/tarefas/{task_id}/desarquivar",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefa_reativar_post",
        "method": "POST",
        "rule": "/api/tarefas/<int:task_id>/reativar",
        "path": "/api/tarefas/{task_id}/reativar",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefa_sugestoes_responsavel_get",
        "method": "GET",
        "rule": "/api/tarefas/<int:task_id>/sugestoes-responsavel",
        "path": "/api/tarefas/{task_id}/sugestoes-responsavel",
        "role": "user",
        "query_string": {"q": "Usuario"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        # Responsáveis MÚLTIPLOS da tarefa (autor/admin). Lista vazia limpa os
        # responsáveis e ainda commita -> 200 (mesma regra de finalizar/campos).
        "id": "api_tarefa_responsaveis_post",
        "method": "POST",
        "rule": "/api/tarefas/<int:task_id>/responsaveis",
        "path": "/api/tarefas/{task_id}/responsaveis",
        "role": "user",
        "json": {"user_ids": []},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    # Fase 5b-2 (Drawer de Tarefa): comentarios (add/editar/excluir) + anexos
    # (listar/upload multipart/download binario/excluir). Anexados ao main_bp em
    # routes/api/task_comments.py e routes/api/task_attachments.py, no envelope
    # (EXCETO o download binario), com api_login_required + permissoes reusadas.
    {
        "id": "api_tarefa_comentario_add_post",
        "method": "POST",
        "rule": "/api/tarefas/<int:task_id>/comentarios",
        "path": "/api/tarefas/{task_id}/comentarios",
        "role": "user",
        "json": {"content": "Comentario via drawer"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_comentario_edit_post",
        "method": "POST",
        "rule": "/api/comentarios/<int:comment_id>",
        "path": "/api/comentarios/{comment_id}",
        "role": "user",
        "json": {"content": "Comentario editado via drawer"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_comentario_delete_post",
        "method": "POST",
        "rule": "/api/comentarios/<int:comment_id>/delete",
        "path": "/api/comentarios/{comment_id}/delete",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefa_anexos_list_get",
        "method": "GET",
        "rule": "/api/tarefas/<int:task_id>/anexos",
        "path": "/api/tarefas/{task_id}/anexos",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefa_anexo_upload_post",
        "method": "POST",
        "rule": "/api/tarefas/<int:task_id>/anexos",
        "path": "/api/tarefas/{task_id}/anexos",
        "role": "user",
        # Magic bytes "%PDF-" casam a extensao .pdf em _file_content_matches_extension.
        "files": {"file": (b"%PDF-1.4\n%fake pdf body for smoke", "doc.pdf")},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_anexo_download_get",
        "method": "GET",
        "rule": "/api/anexos/<int:anexo_id>",
        "path": "/api/anexos/{anexo_id}",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_anexo_delete_post",
        "method": "POST",
        "rule": "/api/anexos/<int:anexo_id>/delete",
        "path": "/api/anexos/{anexo_id}/delete",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_busca_get",
        "method": "GET",
        "rule": "/api/busca",
        "path": "/api/busca",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    # SPA shell (servido via Jinja + csp_nonce; routes/spa.py).
    # Nao exige login: o guard de auth e client-side (carrega /api/me no boot).
    # SPA nos PATHS NATIVOS (item #1): catch-all dinamico que serve o index
    # (Jinja + csp_nonce) nos paths das telas migradas sem rota Jinja propria
    # (ex.: /projetos, /admin/usuarios). Paths nao migrados -> 404.
    {
        "id": "spa_native_path_get",
        "method": "GET",
        "rule": "/<path:spa_path>",
        "path": "/projetos",
        "role": "anon",
        "expected_status": 200,
        "requires_login": False,
        "requires_admin": False,
    },
    # Assets imutaveis do bundle SvelteKit. Com paths.base='' o cliente os pede
    # em /_app/...; esta rota serve a partir de static/spa/_app/.
    {
        "id": "spa_app_asset_get",
        "method": "GET",
        "rule": "/_app/<path:asset_path>",
        "path": "/_app/version.json",
        "role": "anon",
        "expected_status": 200,
        "requires_login": False,
        "requires_admin": False,
    },
    # API and search
    {
        "id": "api_resultados_get",
        "method": "GET",
        "rule": "/api/resultados/<int:objetivo_id>",
        "path": "/api/resultados/1",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_indicadores_get",
        "method": "GET",
        "rule": "/api/indicadores/<int:resultado_id>",
        "path": "/api/indicadores/1",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_templates_get",
        "method": "GET",
        "rule": "/api/templates",
        "path": "/api/templates",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_template_stages_get",
        "method": "GET",
        "rule": "/api/templates/<int:template_id>",
        "path": "/api/templates/{template_id}",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_busca_global_get",
        "method": "GET",
        "rule": "/api/busca-global",
        "path": "/api/busca-global",
        "role": "user",
        "query_string": {"q": "Projeto"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "notifications_dropdown_post",
        "method": "POST",
        "rule": "/api/notificacoes/dropdown",
        "path": "/api/notificacoes/dropdown",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    # Maintenance
    {
        "id": "favicon_get",
        "method": "GET",
        "rule": "/favicon.ico",
        "path": "/favicon.ico",
        "role": "anon",
        "expected_status": [200, 404],
        "requires_login": False,
        "requires_admin": False,
    },
    {
        "id": "calendar_event_generate_meet_post",
        "method": "POST",
        "rule": "/calendarios/eventos/<int:event_id>/gerar-meet",
        "path": "/calendarios/eventos/{calendar_event_id}/gerar-meet",
        "role": "user",
        "expected_status": 302,
        "requires_login": True,
        "requires_admin": False,
    },
    # SPA API — Admin usuarios (envelope canônico; api_admin_required)
    {
        "id": "api_admin_usuarios_list_get",
        "method": "GET",
        "rule": "/api/admin/usuarios",
        "path": "/api/admin/usuarios",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_admin_usuarios_detail_get",
        "method": "GET",
        "rule": "/api/admin/usuarios/<int:user_id>",
        "path": "/api/admin/usuarios/{editable_user_id}",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_admin_usuarios_create_post",
        "method": "POST",
        "rule": "/api/admin/usuarios",
        "path": "/api/admin/usuarios",
        "role": "admin",
        "json": {
            "username": "novo_usuario_api",
            "name": "Novo Usuario API",
            "password": "senhaNova123",
            "orgao": "Orgao Novo",
        },
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_admin_usuarios_update_post",
        "method": "PUT",
        "rule": "/api/admin/usuarios/<int:user_id>",
        "path": "/api/admin/usuarios/{editable_user_id}",
        "role": "admin",
        "json": {"name": "Usuario Editado API", "orgao": "Orgao Editado"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_admin_usuarios_remove_cpf_post",
        "method": "POST",
        "rule": "/api/admin/usuarios/<int:user_id>/remover-cpf",
        "path": "/api/admin/usuarios/{editable_user_id}/remover-cpf",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_admin_usuarios_delete_post",
        "method": "DELETE",
        "rule": "/api/admin/usuarios/<int:user_id>",
        "path": "/api/admin/usuarios/{deletable_user_id}",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    # SPA API — Admin orgaos (arvore) + tipos (envelope; api_admin_required)
    {
        "id": "api_admin_orgaos_tree_get",
        "method": "GET",
        "rule": "/api/admin/orgaos",
        "path": "/api/admin/orgaos",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_admin_orgaos_opcoes_get",
        "method": "GET",
        "rule": "/api/admin/orgaos/opcoes",
        "path": "/api/admin/orgaos/opcoes",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_admin_orgaos_detail_get",
        "method": "GET",
        "rule": "/api/admin/orgaos/<int:orgao_id>",
        "path": "/api/admin/orgaos/{orgao_child_id}",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    # SPA API — Integração SIORG (contrato cru, sem envelope; api_admin_required)
    {
        "id": "api_admin_siorg_status_get",
        "method": "GET",
        "rule": "/api/admin/siorg/status",
        "path": "/api/admin/siorg/status",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        # Sem SIORG_API_KEY no app de teste: a rota curto-circuita em 503
        # "não configurada" antes de construir o client (sem backoff/retry).
        "id": "api_admin_siorg_sync_post",
        "method": "POST",
        "rule": "/api/admin/siorg/sync",
        "path": "/api/admin/siorg/sync",
        "role": "admin",
        "expected_status": 503,
        "requires_login": True,
        "requires_admin": True,
    },
    # SPA API — Admin templates de etapas (envelope; api_admin_required)
    {
        "id": "api_admin_templates_list_get",
        "method": "GET",
        "rule": "/api/admin/templates",
        "path": "/api/admin/templates",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_admin_templates_detail_get",
        "method": "GET",
        "rule": "/api/admin/templates/<int:template_id>",
        "path": "/api/admin/templates/{template_id}",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_admin_templates_create_post",
        "method": "POST",
        "rule": "/api/admin/templates",
        "path": "/api/admin/templates",
        "role": "admin",
        "json": {
            "name": "Template Novo API",
            "description": "Criado nos testes via API",
            "stages": [{"name": "Etapa A", "duration_days": 2}],
        },
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_admin_templates_update_post",
        "method": "PUT",
        "rule": "/api/admin/templates/<int:template_id>",
        "path": "/api/admin/templates/{template_id}",
        "role": "admin",
        "json": {
            "name": "Template Editado API",
            "description": "Atualizado nos testes via API",
            "stages": [{"name": "Etapa B", "duration_days": 4}],
        },
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_admin_templates_duplicate_post",
        "method": "POST",
        "rule": "/api/admin/templates/<int:template_id>/duplicate",
        "path": "/api/admin/templates/{template_id}/duplicate",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_admin_templates_delete_post",
        "method": "DELETE",
        "rule": "/api/admin/templates/<int:template_id>",
        "path": "/api/admin/templates/{template_id}",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    # Fase 6 (Google Calendar): hub JSON + acoes de conexao Google no envelope.
    {
        "id": "api_calendarios_hub_get",
        "method": "GET",
        "rule": "/api/calendarios",
        "path": "/api/calendarios",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        # Membros do Time visíveis no calendário (usuários do mesmo órgão + admins).
        "id": "api_calendarios_membros_get",
        "method": "GET",
        "rule": "/api/calendarios/membros",
        "path": "/api/calendarios/membros",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_calendarios_google_disconnect_post",
        "method": "POST",
        "rule": "/api/calendarios/google/disconnect",
        "path": "/api/calendarios/google/disconnect",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_calendarios_google_sync_post",
        "method": "POST",
        "rule": "/api/calendarios/google/sync",
        "path": "/api/calendarios/google/sync",
        "role": "user",
        "expected_status": 409,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_calendarios_google_watch_renew_post",
        "method": "POST",
        "rule": "/api/calendarios/google/watch/renew",
        "path": "/api/calendarios/google/watch/renew",
        "role": "user",
        "expected_status": 409,
        "requires_login": True,
        "requires_admin": False,
    },
]

LOGIN_REQUIRED_CASES = [case for case in ROUTE_CASES if case["requires_login"]]
ADMIN_REQUIRED_CASES = [case for case in ROUTE_CASES if case["requires_admin"]]

ROUTE_CASES += [
    {
        "id": "api_projeto_criar_post",
        "method": "POST",
        "rule": "/api/projetos",
        "path": "/api/projetos",
        "role": "user",
        "json": {
            "titulo": "Projeto via API",
            "orgao_id": "{auditoria_orgao_id}",
            "prioridade": "media",
        },
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        # Import de projetos via CSV (Admin) — sucessor de /projects/import.
        # Sem corpo, o handler valida e devolve 422 (órgão obrigatório).
        "id": "api_projetos_importar_csv_post",
        "method": "POST",
        "rule": "/api/projetos/importar-csv",
        "path": "/api/projetos/importar-csv",
        "role": "admin",
        "expected_status": 422,
        "requires_login": True,
        "requires_admin": True,
    },
    {
        "id": "api_projeto_concluir_post",
        "method": "POST",
        "rule": "/api/projetos/<int:project_id>/concluir",
        "path": "/api/projetos/{project_complete_id}/concluir",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_catalogo_objetivos_get",
        "method": "GET",
        "rule": "/api/catalogos/objetivos",
        "path": "/api/catalogos/objetivos",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_etapa_tarefas_get",
        "method": "GET",
        "rule": "/api/projetos/<int:project_id>/etapas/<int:etapa_id>/tarefas",
        "path": "/api/projetos/{project_id}/etapas/{etapa_id}/tarefas",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefa_criar_post",
        "method": "POST",
        "rule": "/api/tarefas",
        "path": "/api/tarefas",
        "role": "user",
        "json": {
            "project": "{project_id}",
            "descricao": "Tarefa via API",
            "status": "nao_iniciada",
        },
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefa_excluir_post",
        "method": "POST",
        "rule": "/api/tarefas/<int:task_id>/excluir",
        "path": "/api/tarefas/{task_id}/excluir",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefa_mover_etapa_post",
        "method": "POST",
        "rule": "/api/tarefas/<int:task_id>/mover-etapa",
        "path": "/api/tarefas/{task_id}/mover-etapa",
        "role": "user",
        "json": {"etapa_id": "{etapa_started_id}"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_tarefas_arquivar_finalizadas_post",
        "method": "POST",
        "rule": "/api/tarefas/arquivar-finalizadas",
        "path": "/api/tarefas/arquivar-finalizadas",
        "role": "user",
        "json": {},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_hub_sugestoes_responsavel_get",
        "method": "GET",
        "rule": "/api/tarefas/sugestoes-responsavel",
        "path": "/api/tarefas/sugestoes-responsavel",
        "role": "user",
        "query_string": {"project": "{project_id}"},
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_project_meeting_create_post",
        "method": "POST",
        "rule": "/api/projetos/<int:project_id>/reunioes",
        "path": "/api/projetos/{project_id}/reunioes",
        "role": "user",
        "json": {
            "title": "Reuniao via API",
            "starts_at": "2026-04-01T10:00",
            "ends_at": "2026-04-01T11:00",
        },
        # Sem conexao Google ativa no seed => 400 (mesma regra do legado).
        "expected_status": 400,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_project_meeting_edit_post",
        "method": "POST",
        "rule": "/api/etapas/<int:etapa_id>/reuniao",
        "path": "/api/etapas/{etapa_id}/reuniao",
        "role": "user",
        "json": {
            "title": "Reuniao editada via API",
            "starts_at": "2026-04-01T10:00",
            "ends_at": "2026-04-01T11:00",
        },
        # Etapa regular do seed nao e reuniao Google editavel => 400.
        "expected_status": 400,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_project_meeting_delete_post",
        "method": "POST",
        "rule": "/api/etapas/<int:etapa_id>/reuniao/excluir",
        "path": "/api/etapas/{etapa_id}/reuniao/excluir",
        "role": "user",
        # Etapa regular do seed nao e reuniao Google => 422 (mesma regra do
        # legado: exclusao de reuniao so vale para etapas-reuniao Google).
        "expected_status": 422,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_calendar_event_create_post",
        "method": "POST",
        "rule": "/api/calendarios/eventos",
        "path": "/api/calendarios/eventos",
        "role": "user",
        "json": {
            "title": "Evento via API",
            "starts_at": "2026-04-02T09:00",
            "ends_at": "2026-04-02T10:00",
        },
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_calendar_event_edit_post",
        "method": "POST",
        "rule": "/api/calendarios/eventos/<int:event_id>/editar",
        "path": "/api/calendarios/eventos/{calendar_event_id}/editar",
        "role": "user",
        "json": {
            "title": "Evento editado via API",
            "starts_at": "2026-04-02T09:00",
            "ends_at": "2026-04-02T10:00",
        },
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_calendar_event_generate_meet_post",
        "method": "POST",
        "rule": "/api/calendarios/eventos/<int:event_id>/gerar-meet",
        "path": "/api/calendarios/eventos/{calendar_event_id}/gerar-meet",
        "role": "user",
        # Sem conexao Google ativa no seed => 409 (mesma regra do legado).
        "expected_status": 409,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_calendar_event_delete_post",
        "method": "POST",
        "rule": "/api/calendarios/eventos/<int:event_id>/excluir",
        "path": "/api/calendarios/eventos/{calendar_event_id}/excluir",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    # SPA aditivos (Fase atual): exclusao real de projeto, notificacoes enveloped
    # e arvore de orgao do escopo (seletor da topnav).
    {
        "id": "api_projeto_excluir_delete",
        "method": "DELETE",
        "rule": "/api/projetos/<int:project_id>",
        "path": "/api/projetos/{project_id}",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_notificacoes_list_get",
        "method": "GET",
        "rule": "/api/notificacoes",
        "path": "/api/notificacoes",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_notificacoes_marcar_lidas_post",
        "method": "POST",
        "rule": "/api/notificacoes/marcar-lidas",
        "path": "/api/notificacoes/marcar-lidas",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_orgaos_escopo_get",
        "method": "GET",
        "rule": "/api/orgaos/escopo",
        "path": "/api/orgaos/escopo",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    # Membros do projeto (convites, S4/F3-11..F3-12). CONVITES_HABILITADOS nasce
    # off (config.py) e o app de teste nao liga a flag: as 5 rotas respondem o
    # 404 anti-enumeracao aqui. O comportamento com a flag ligada esta em
    # tests/routes/test_api_project_members_contract.py.
    {
        "id": "api_projeto_membros_list_get",
        "method": "GET",
        "rule": "/api/projetos/<int:project_id>/membros",
        "path": "/api/projetos/{project_id}/membros",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projeto_membro_criar_post",
        "method": "POST",
        "rule": "/api/projetos/<int:project_id>/membros",
        "path": "/api/projetos/{project_id}/membros",
        "role": "user",
        "json": {"user_id": 999999, "papel": "leitor"},
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projeto_membro_atualizar_put",
        "method": "PUT",
        "rule": "/api/projetos/<int:project_id>/membros/<int:member_id>",
        "path": "/api/projetos/{project_id}/membros/1",
        "role": "user",
        "json": {"papel": "leitor"},
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projeto_membro_revogar_delete",
        "method": "DELETE",
        "rule": "/api/projetos/<int:project_id>/membros/<int:member_id>",
        "path": "/api/projetos/{project_id}/membros/1",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projeto_membros_lote_post",
        "method": "POST",
        "rule": "/api/projetos/<int:project_id>/membros/lote",
        "path": "/api/projetos/{project_id}/membros/lote",
        "role": "user",
        "json": {"orgao_id": 999999, "papel": "leitor"},
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_usuarios_busca_get",
        "method": "GET",
        "rule": "/api/usuarios/busca",
        "path": "/api/usuarios/busca",
        "role": "user",
        "query_string": {"q": "usu"},
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    # Relatorio admin de grants orfaos (S4/F3-25; api_admin_required, sem gate
    # de flag: revisar convites ja gravados vale mesmo com CONVITES_HABILITADOS
    # off).
    {
        "id": "api_admin_grants_orfaos_get",
        "method": "GET",
        "rule": "/api/admin/relatorios/grants-orfaos",
        "path": "/api/admin/relatorios/grants-orfaos",
        "role": "admin",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": True,
    },
    # Colecoes de projetos (Fase 1). As rotas com <collection_id> usam um id
    # inexistente: o seed nao semeia colecao e o contrato manda responder 404
    # anti-enumeracao (colecao inexistente e colecao de outro dono sao
    # indistinguiveis). Indice e toggle de favorito exercem o caminho feliz.
    {
        "id": "api_colecoes_list_get",
        "method": "GET",
        "rule": "/api/colecoes",
        "path": "/api/colecoes",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_colecao_criar_post",
        "method": "POST",
        "rule": "/api/colecoes",
        "path": "/api/colecoes",
        "role": "user",
        "json": {
            "nome": "Colecao via API",
            "descricao": "Criada no smoke",
            "icone": "camadas",
            "cor": "primary",
        },
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_colecao_atualizar_put",
        "method": "PUT",
        "rule": "/api/colecoes/<int:collection_id>",
        "path": "/api/colecoes/999999",
        "role": "user",
        "json": {"nome": "Colecao renomeada"},
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_colecao_apagar_delete",
        "method": "DELETE",
        "rule": "/api/colecoes/<int:collection_id>",
        "path": "/api/colecoes/999999",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_colecao_projetos_list_get",
        "method": "GET",
        "rule": "/api/colecoes/<int:collection_id>/projetos",
        "path": "/api/colecoes/999999/projetos",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_colecao_projeto_adicionar_post",
        "method": "POST",
        "rule": "/api/colecoes/<int:collection_id>/projetos",
        "path": "/api/colecoes/999999/projetos",
        "role": "user",
        "json": {"project_id": 999999},
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_colecao_projeto_remover_delete",
        "method": "DELETE",
        "rule": "/api/colecoes/<int:collection_id>/projetos/<int:project_id>",
        "path": "/api/colecoes/999999/projetos/{project_id}",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_projeto_favorito_post",
        "method": "POST",
        "rule": "/api/projetos/<int:project_id>/favorito",
        "path": "/api/projetos/{project_id}/favorito",
        "role": "user",
        "expected_status": 200,
        "requires_login": True,
        "requires_admin": False,
    },
    # Colecoes de projetos (Fase 2): compartilhamentos (so dono) + cronograma.
    # Mesmo id inexistente da Fase 1: sem colecao semeada, o gate responde 404
    # anti-enumeracao antes de olhar papel ou payload.
    {
        "id": "api_colecao_shares_list_get",
        "method": "GET",
        "rule": "/api/colecoes/<int:collection_id>/compartilhamentos",
        "path": "/api/colecoes/999999/compartilhamentos",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_colecao_share_criar_post",
        "method": "POST",
        "rule": "/api/colecoes/<int:collection_id>/compartilhamentos",
        "path": "/api/colecoes/999999/compartilhamentos",
        "role": "user",
        "json": {"user_id": 999999, "papel": "viewer"},
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_colecao_share_revogar_delete",
        "method": "DELETE",
        "rule": "/api/colecoes/<int:collection_id>/compartilhamentos/<int:share_id>",
        "path": "/api/colecoes/999999/compartilhamentos/999999",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_colecao_cronograma_get",
        "method": "GET",
        "rule": "/api/colecoes/<int:collection_id>/cronograma",
        "path": "/api/colecoes/999999/cronograma",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
    # Sugestao de colecoes por IA: a suite roda sem WATSONX_API_KEY, entao o gate
    # de credencial responde 503 antes de qualquer chamada ao provedor (nenhum
    # teste faz I/O de rede).
    {
        "id": "api_colecao_sugestoes_post",
        "method": "POST",
        "rule": "/api/colecoes/sugestoes",
        "path": "/api/colecoes/sugestoes",
        "role": "user",
        "expected_status": 503,
        "requires_login": True,
        "requires_admin": False,
    },
    # Cache de sugestoes (IA Fase 2): o GET compartilha o gate 503 do POST; o
    # descarte NAO tem gate de IA e responde 404 anti-enumeracao sem linha
    # semeada (espelho de api_colecao_cronograma_get).
    {
        "id": "api_colecao_sugestoes_get",
        "method": "GET",
        "rule": "/api/colecoes/sugestoes",
        "path": "/api/colecoes/sugestoes",
        "role": "user",
        "expected_status": 503,
        "requires_login": True,
        "requires_admin": False,
    },
    {
        "id": "api_colecao_sugestao_descartar_post",
        "method": "POST",
        "rule": "/api/colecoes/sugestoes/<int:sugestao_id>/descartar",
        "path": "/api/colecoes/sugestoes/999999/descartar",
        "role": "user",
        "expected_status": 404,
        "requires_login": True,
        "requires_admin": False,
    },
]
