from pathlib import Path


def test_dark_mode_stylesheet_contains_critical_interaction_selectors():
    css_path = Path(__file__).resolve().parents[2] / 'static' / 'theme-dark.css'
    css = css_path.read_text(encoding='utf-8')

    required_fragments = [
        'Interaction Hardening',
        '.main-content .btn',
        '.btn-primary',
        '.btn-task-primary',
        '.btn-projects-v4-primary',
        '.btn-pending-primary',
        '.btn-template-primary',
        '.project-create-btn-primary',
        '.btn-task-danger',
        '.projects-v4-action-btn.is-delete',
        '.badge',
        '.priority-badge',
        '.projects-v4-badge',
        '.pending-chip-atrasada',
        '.tasks-chip',
        '.task-item-priority-chip',
        '.task-items-kanban-badge',
        '.task-items-list',
        '.task-item-header-row',
        '.task-item-row',
        '.task-item-add-row',
        '.task-items-kanban-column',
        '.task-items-kanban-dropzone',
        '.task-items-kanban-card',
        '.task-items-view-toggle',
        '.task-item-drawer',
        '.task-item-drawer-header',
        '.task-item-drawer-textarea',
        '.task-item-drawer-select',
        '.task-item-drawer-comments',
        '.task-item-drawer-comment-form',
        '.task-item-drawer-anexos',
        '.task-item-drawer-anexos-upload-btn',
        '.task-item-drawer-delete-confirm',
        '.task-anexo-preview-modal',
        '.task-anexo-preview-dialog',
        '.task-anexo-preview-link',
        '.search-results-count',
        '.search-result-badge-project',
        '.project-compact-inner',
        '.project-compact-dates span',
        '.objective-section',
        '.additional-info-box',
        '.etapa-v4-table-card',
        '.etapa-v4-table thead th',
        '.etapa-inline-entry-btn',
        '.etapa-inline-input',
        '.bg-success-light',
        '.comentario-textarea-inline',
        '#importModelModal .modal-content',
        '.custom-context-menu',
        '.confirm-modal',
        '.task-comment-btn',
        '.etapa-inline-icon-btn',
        '.history-field input',
        '.history-list-header',
        '.history-action-pill.tone-success',
        '.header-count',
        '.template-stages-count',
        '.glass-stage-item-template',
        '.account-page-header-main',
        '.account-input',
        '.account-area-item',
        '.account-admin-panel',
        '.app-notification-leading',
        '.app-notification-main',
        '.app-notification-row',
        '.app-notification-time',
        '.app-notification-subline',
        '.app-notification-unread-dot',
        '.app-notification-icon-wrap',
        '.app-notification-item.is-unread',
        '.task-item-row:hover',
        ':focus-visible',
        ':disabled',
    ]

    missing = [fragment for fragment in required_fragments if fragment not in css]
    assert not missing, f'Selectors obrigatórios ausentes no dark mode: {missing}'
